### ISSUE TITLE
[In progress] Geospatial data - How to update new layers  

### ISSUE THREAD

**Issue by carlabiscotti** [Orcasa-Platform/orcasa#113]
User story: As an admin user (Emilie and Mathieu) I want to know how to add new layers to the Geospatial data module.

Acceptance criteria: 
- Relevant documentation and information is provided.
- The documentation is shared in a common place.

**Comment by carlabiscotti** [comment]
Hi Emilie, just an update on this the first version of the documentation for updating layers has been completed by Clement. Álvaro and Ángel will review it within this sprint so that we can share it with you when delivering V1 of the platform.

**Comment by EmilieVrot** [comment]
This issue has been adressed
