### ISSUE TITLE
[QA] Homepage - The color in the projects indicator should be blue (representing the Network module)

### ISSUE THREAD

**Issue by carlabiscotti** [Orcasa-Platform/orcasa#115]
![Captura de Pantalla 2023-12-18 a las 16 05 46](https://github.com/Orcasa-Platform/orcasa/assets/97748487/373eed00-550b-48b6-a879-9ee340132074)

**Comment by carlabiscotti** [comment]
This adjustment has been implemented. You can check it on the demo environment.

**Comment by EmilieVrot** [comment]
Thanks it is ok
