### ISSUE TITLE
[QA] Review the name of the "labels" setting

### ISSUE THREAD

**Issue by carlabiscotti** [Orcasa-Platform/orcasa#116]
When reviewing the map settings, it wasn't clear to Emilie what the "Labels" toggle was for. The name "Label" is generic and does not fully describe what is behind it, maybe we could name it "Country labels" instead?

![Captura de Pantalla 2023-12-18 a las 16 13 04](https://github.com/Orcasa-Platform/orcasa/assets/97748487/031c08e2-b120-42ac-a986-6226f67211ad)

**Comment by EmilieVrot** [comment]
Thanks it is ok
