### ISSUE TITLE
[QA] Network - Adding an organisation in the FO (bugs)

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#124]
Hello Carla,

Firstly, I wish you a happy new year!

Here are some bugs I encountered when creating a new organisation in the FO (id: 170 "AGES - Austrian Agency for Health and Food Safety Ltd"):

1. Name: the limit of 150 caracters does not apply. We have it in the BO.
2. Organisation type: display the values in this order: ![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/6ad8a0d5-799f-4198-af02-7f416c40a3f3)
3. Main thematic : the first one is compulsory (same bug in the BO)
4. Thematic: display the values in this order: ![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/573e4733-6bf8-4260-a5b7-a604d7db73ff)
5. Website: it is a compulsory field (same bug in the BO)
6. Website: I have this error, while in BO I was able to enter it: ![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/8d123f16-b5af-4612-a293-d51058638dd2)
7. In FO, the fact that duplicates are not detected is troublesome. Is it possible to suggest existing results based on X similar characters?
8. As a BO administrator, I did not receive any email notification to approve the proposed entry.

Best,
Emilie

**Comment by carlabiscotti** [comment]
Hi Emilie, 

Thank you for your feedback. Items 1 to 6 we'll address for version 1. For items 7 and 8 I created other items to track them separately since they won't be implemented in version 1.

Best, 
Carla

**Comment by EmilieVrot** [comment]
Thanks Carla

**Comment by carlabiscotti** [comment]
Emilie, Items 1 to 6 are fixed in staging.

**Comment by carlabiscotti** [comment]
Hi Emilie, 
Items 2 and 4 (changing the order in which the options display in the multiple values fields), won't be implemented for V1.
I will add a separate item for that. Please notice that this functionality is not currently available in strapi and Tiago needs to investigate how to do that. Once it is done, you should be able to sort the dropdowns from the back office.

**Comment by EmilieVrot** [comment]
ok I am closing this one
