### ISSUE TITLE
[QA] Network - Bug on the map

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#126]
With the project ClieNFarm, one organisation is not located correctly on the map:

![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/fbbfbba2-5816-4fbf-bff8-247530a27439)
![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/fd2afe45-ef38-4023-81e9-021b2e1ba002)

**Comment by carlabiscotti** [comment]
Hi Emilie, this is fixed. Please take a look and let us know any comments, thanks.

**Comment by EmilieVrot** [comment]
Thanks it is working
