### ISSUE TITLE
[New] Network - Adding a project in the BO (bugs) 

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#128]
These fields should be compulsory:
- Lead partner
- Project type
- Country of coordination

**Comment by carlabiscotti** [comment]
Hi Emilie, as I mentioned yesterday, it is not possible within Strapi to set this kind of field as mandatory. I will ask whether it is possible to add a help text for the admin users.

**Comment by carlabiscotti** [comment]
Hi Emilie, Tiago needs to investigate this. I've created a separate item, #139 to track this and #127 together.
