### ISSUE TITLE
[To discuss] Network - Notify admin users when projects/organizations need to be reviewed 

### ISSUE THREAD

**Issue by carlabiscotti** [Orcasa-Platform/orcasa#136]
As a BO administrator, I want to be notified when new organizations and/or projects are added from the front end so that I can access the BO to review and approve them.

**Acceptance criteria:**

1. Address to send the notifications: [impact4soil@renater.fr](mailto:impact4soil@renater.fr)
2. Only one notification by day including the number of proposed projects and the number of proposed organizations
3. No notification if there were no proposed projects nor organisations during the day
4. In the notification, a link to Strapi Content manager

**Comment by EmilieVrot** [comment]
Hi Carla, can we change it for  (To do]?

**Comment by carlabiscotti** [comment]
It's "to discuss" because it's not fully ready to be implemented by the team, we need to work on the acceptance for this story: when notifications are sent, to whom, what should they say, etc. I don't think this was defined in detail in the technical specifications doc. Could you share with us what are the expectations on the user side?

**Comment by EmilieVrot** [comment]
Hi Carla,

Here the answer:

- Adress to send the notifications: impact4soil@renater.fr
- Only one notification by day including the number of proposed projects and the number of proposed organizations
- No notification if there was no proposed projects nor organisations during the day
- In the notification, a link to Strapi Content manager

Thanks

**Comment by carlabiscotti** [comment]
Hi Emilie, thank you for your responses. I will keep this item "To discuss" until the team can review and confirm if further information is needed. Thanks.

**Comment by EmilieVrot** [comment]
Hi Carla,

Ok please let me know when you get a feedback.

Best

**Comment by EmilieVrot** [comment]
JIRA #ORC-411
