### ISSUE TITLE
[To do] Network - Help text for admin users 

### ISSUE THREAD

**Issue by carlabiscotti** [Orcasa-Platform/orcasa#139]
**Context:** Some fields are mandatory but can't be set as such in the back office due to Strapi's limitations. We want to prevent admins users from adding projects/organizations without these fields. 

**Description**: investigate if it is possible to add help text to these fields to let users know they are mandatory. 

Project form:
- Lead partner
- Project type
- Country of coordination

Organization form:
Organization type
Main organization theme
Country

**Comment by EmilieVrot** [comment]
JIRA #ORC-410
