### ISSUE TITLE
[New] - Display the map according to the screen size

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#140]
Hello Carla,

On certain screen displays (e.g., 13-inch screens), the visualization of the map is not optimal. The map is cut off, and the scale takes up half of the map. The user has to zoom out for it to be readable. Will the responsive mode address this issue?

Thanks,
Emilie

**Comment by carlabiscotti** [comment]
Hi Emilie, can you please share some screenshots or screen recordings sharing what you mean? Thank you.

**Comment by CV-Gate** [comment]
@EmilieVrot,
Responsive design optimizes display across various devices by adjusting layout and content. However, it's important to recognize that responsiveness has limitations, especially for applications requiring geographical data presentation, such as maps. Even in responsive mode, the physical dimensions of smaller screens can restrict the amount of information we can display simultaneously.

At maximum zoom level, where the map is set to show a global view, smaller screens' constraints may necessitate user interaction, such as panning, to fully comprehend the map's scope. This is the behavior you could expect for any map visualization. The interface elements, or even the browser, might occlude some regions on these displays, reflecting the screen size limitations. This doesn't occur with other media elements such as photos, as these can be safely scaled down.

**Comment by EmilieVrot** [comment]
JIRA #ORC-498
