### ISSUE TITLE
[New] Network - Modification of organization/project in strapi

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#144]
If I modify an organization or project in Strapi (BO), saving alone is not sufficient; I also need to reset the status to 'Accepted.' This should remain automatically set to 'Accepted,' as it does when creating a new organization/project. 

As a result, I lost all the modifications made at the beginning of January (yet I did receive a pop up message confirming that they were saved). Is there a way to retrieve them?

Thanks

**Comment by tiagojsag** [comment]
I just tested this on demo, and modified two projects: one with no publication status, and another with publication status = accepted. In both scenarios, I modified the name and reloaded the page. In both scenarios, the name was modified, and the status was not - which is as expected. I then changed the name back to its original value, and it also saved as expected. So, without any additional details, I cannot reproduce the issue you are describing.

Please provide additional details so we can reproduce the issue you described:
- which project/org did you modify?
- what modification did you make?
- what was the "publication status" prior to your changes?

thank you

**Comment by EmilieVrot** [comment]
Hello Tiago,

I think there is an issue.
I have made a lot of modifications in strapi during the first week of January.

I remembered updating a lot of projects and organizations who were missiong partners.
For instance the ORCaSa project.
When I did that, I checked in the development application that my corrections applied. They did.

Nowadays, I can see that the ORCaSa project is not published and is missing a lot of partners.
Other exemples: AnimalChange, AGROECOseqC, etc.

Can you have a look in the log of the application?
Thanks

**Comment by tiagojsag** [comment]
Hi Emily,

Logs only record that changes were made, but they do not record the content of those changes.

If these changes were made during the first week of January, it also means this is now outside of our backup window, which is 5 days for non-production deployments such as demo. 

The information that you modified the ORCaSa project, and associated different partners with it does partially answer the questions I asked in my previous message, but it would be great if you could provide the additional info  I requested: do you remember the what was the "publication status" prior to your change?

Answering these questions will hopefully help me reproduce the issue you are reporting. Without being able to reproduce the problem, I cannot know the root cause, and thus I cannot fix it.

Thank you

**Comment by tiagojsag** [comment]
Thanks for the update.

I'll update the backup window to a month, I'll let you know once it's done.

At this stage, it does not seem possible to recover the previous data, so it might be necessary to input it manually once again. However, before that, I do want to look further into this to figure out what happened. I will let you know once I am done with the investigation, so we are sure we are bug-free.

Thanks

**Comment by EmilieVrot** [comment]
Ok thanks. Please let me know as soon as possible as I have new items to enter.

**Comment by EmilieVrot** [comment]
Hello Tiago,

Any feedback on this issue?

Thanks,
Emilie

**Comment by EmilieVrot** [comment]
Message from Miguel on January 30th: 

we can do a partial import for the lost data, so, you can go ahead and use the latest data template and we'll take care of merging it in the "demo" environment.

**Comment by EmilieVrot** [comment]
Hello Miguel,

A quick question on this. I am working on the Excel file for the import.

- 90 organizations have been created directly in Strapi (id 133 to 222). Same thing for projects 26 to 30.
Can you export me all the data for them, so that I can integrate them in the model? It will take too much time to add them manually in the Excel file.

Thanks,
Emilie

**Comment by EmilieVrot** [comment]
#ORC-461
