### ISSUE TITLE
[New] Network - Change of the project corrdinator in Front Office and its impact in Strapi

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#145]
I assigned CIRAD as the coordinator of the MRV4SOC project. 

However, in the Front Office, if I created another organization (GMV) and set it as the coordinator for MRV4SOC: it overwrited it in Strapi, even before I have validated the organization in Strapi. 

This should at least wait for my validation in Strapi.

**Comment by tiagojsag** [comment]
I was able to reproduce this behavior and identify the root cause. Permanently fixing it will require substantial changes and some time. Since the current implementation may lead to data corruption, we'll be temporarily disabling this feature on the FE. Once the fix is in place, we'll reenable it

**Comment by EmilieVrot** [comment]
Thank you Tiago

What feature will you be disabling in the FE?

**Comment by EmilieVrot** [comment]
ok

**Comment by EmilieVrot** [comment]
JIRA #ORC-409
