### ISSUE TITLE
[QA] Network - Adding a project in the Front Office with the organization missing

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#146]
« If the organisation you are looking for is not on the list, please use the organisation form to add it first. " --> It would be helpful to include the link here to the form for adding an organization.

**Comment by carlabiscotti** [comment]
Hi Emilie, this has been implemented in staging and will be deployed to demo at the end of the current sprint.

**Comment by EmilieVrot** [comment]
Thnaks, it is ok in the staging environment.

**Comment by EmilieVrot** [comment]
it is ok in demo also
