### ISSUE TITLE
[QA] Network - Adding a project/organisation in the Front Office - Bug on the url

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#148]
I have the same issue for organisation and project:

![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/6c66c36b-bfb2-4501-96f4-64984d2a06b2)

**Comment by carlabiscotti** [comment]
Emilie, this issue and the one in the Organization form (https://github.com/Orcasa-Platform/orcasa/issues/124) are solved in staging. You can review it there. It will deploy to demo at the end of this sprint.

**Comment by EmilieVrot** [comment]
Hello carla,

Thanks it's working in staging.

**Comment by EmilieVrot** [comment]
Hello Miguel,

I am not able to add new project or organisation in the demo environment.

Is it normal?

**Comment by EmilieVrot** [comment]
This problem has been resolved
