### ISSUE TITLE
[New] Network - Project form - Prevent users from selecting the same "Area of intervention" more then once

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#152]
If select a value for the Main area of intervention, we shouldn't be able to select it again in the field "Second area of intervention".
Same thing for the "Third area of intervention".

**Comment by carlabiscotti** [comment]
Hi Emilie, I noticed there are several improvements related to the forms that make the logic more complex and will require a considerable amount of work and back and forth. We will need to prioritize this work along with other features/feedback/enhancements we have in the backlog. My suggestion is that we shouldn't invest much more effort in the forms until we have actual users using them. I just wanted to point this out for your consideration.

**Comment by EmilieVrot** [comment]
Hello Carla,

I think this rule is quite standard in fields that appear multiple times. I'll leave it prioritized in version 2 as a minor bug.

Thanks

**Comment by EmilieVrot** [comment]
JIRA #ORC-404
