### ISSUE TITLE
[To discuss] Network - Sustainable development goal field should admit multiple values  (FO and BO)

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#153]
Can you multivalued this field?

Thanks

**Comment by carlabiscotti** [comment]
Hi Emilie, to prevent back and forth. Can you please detail the acceptance criteria for this request? Thank you.

**Comment by EmilieVrot** [comment]
Hello Carla,

Users should be able to add multiple values for the field "Sustainable development goal" in BO and in FO. It is for a project.

Does it answer your request?

Best

**Comment by EmilieVrot** [comment]
JIRA #ORC-403
