### ISSUE TITLE
[To discuss] Network - Add the field "Land use type" in projects

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#157]
Hello Carla,

For the projects in the Network module, we would like to add this field:

Name: Land use type
Can be multivalued
Optional
Values:
- Cropland
- Forest Land
- Grassland
- Wetlands
- Other Land

It should be the same field used for Practices.

Thanks,
Emilie

**Comment by carlabiscotti** [comment]
Hi Emilie, 

Could you share a bit more about the objective behind this change? How does this help users? 

Would this information be available for the projects in the Network? I feel that most of the projects won't have a land use type.

**Comment by EmilieVrot** [comment]
Hello Carla, 

The objective is to integrate new types of projects which are schemes. We nned that info for those types of projects.
But it shouldn't be complsory for the others.

Thanks

**Comment by EmilieVrot** [comment]
JIRA #ORC-460
