### ISSUE TITLE
[New] - Network - Add the definition of Carbon farming schemes (one of the project types)

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#160]
Hello Carla, 

Is it possible to add somewhere in the network module, a definition of a carbon farming scheme (which is a project type)?
Maybe in the introduction, like this:

You can search by organisations or projects (research projects, living labs, storage project or carbon farmin scheme). 
A carbon farmin scheme is any voluntary agreement in which a farmer or a group of farmers commit themselves to apply carbon farming measures in return for a payment in any form. Users will be able to see how existing schemes work and how farmers in Europe and beyond are being rewarded for implementing different types of carbon farming practices. 

What do you think?
Best

**Comment by carlabiscotti** [comment]
Hi Emilie, 

Why is this information particularly valuable for the users? What about the rest of the project types? 

What is the use case in which this information is needed? Based on your message it seems to me that you'd like to share this information with users who are exploring the list, what about users that are adding new projects? When in the user journey does the user need to see this information?

Are there other definitions that are relevant for the users?

**Comment by EmilieVrot** [comment]
Hello Carla,

The objective we have with Julien and Mathieu is to integrate all the schemes from the Road4Schemes platform into the Network module. 

Instead of asking you to create a third type (the first two being Organization and Projects), we have decided to integrate them as project types. To achieve this, we need to add a specific (non-mandatory) field (in another ticket), and we want to include a definition of the schemes. 

It is true that this definition will also be useful when creating a project. I believe that, in general, it would be helpful to define each of the different types of projects, and perhaps, in this case, through a tooltip rather than the introductory text on the page. 

What do you think?

Best,
Emilie

**Comment by EmilieVrot** [comment]
JIRA #ORC-459
