### ISSUE TITLE
[To do] Network - Organization form - Display value entered manually when organization type is "Other"

### ISSUE THREAD

**Issue by carlabiscotti** [Orcasa-Platform/orcasa#163]
When the type of organization is “Other”, the value entered manually should be displayed (ex: Promotional Centre for Family Farming – CPP)
![image](https://github.com/Orcasa-Platform/orcasa/assets/97748487/fb6fe6df-ee3c-4302-82a6-bc8f49242eae)

**Comment by EmilieVrot** [comment]
JIRA #ORC-399
