### ISSUE TITLE
[To discuss] Network - Different colors for adding projects and organizations buttons

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#17]

**Comment by EmilieVrot** [comment]
Can you use the same colors to add an organisation or a project?

**Comment by carlabiscotti** [comment]
Emilie, 
This is how the buttons for adding an organization and a project will look like. It is the way Lidia has defined it ensuring looks clean and it is consistent with the overall design and also ensuring it makes sense for users. At this point, I want to prevent any further back and forths on this kind of decisions to safeguard the budget we have available for the project. Once users start using the platform we'll receive feedback from them, let's wait until then to see if this change is needed.

![image](https://github.com/Orcasa-Platform/orcasa/assets/97748487/0e1a5d42-c0fc-4155-9a1c-292a5d7cb8b5)

**Comment by EmilieVrot** [comment]
Hello Carla, instead of discarded, can we leave it ay "To discuss"?

**Comment by EmilieVrot** [comment]
Yes I agree

**Comment by EmilieVrot** [comment]
Hello,

I will close this issue. We will leave the buttons as defined by the designer. Thanks
