### ISSUE TITLE
Network - Limit of characters for the fields "Short description" and "Description"

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#20]
This followed those Base camp issues: https://basecamp.com/1756858/projects/19116498/todos/485217328 
https://basecamp.com/1756858/projects/19116498/messages/105635538 

It seems ok to keep a maximal length of 350 caracters for the short description.

For the long description, can we keep a maximum limit of 3,000 caracters and have a + button to show the text after the 600 caracters? We can discuss it when we will see the development of the detailed view.

**Comment by carlabiscotti** [comment]
Hi Emilie, 
This is already implemented. We can close this issue.

**Comment by EmilieVrot** [comment]
Thanks
Yet I think the need for a + button will be required when you will add the links between actors and organizations. What do you think?

**Comment by carlabiscotti** [comment]
I don't know. But that should be solved if the issue appears. The design and development team will solve any inconsistencies if they appear. On our side, we can check if this is an actual issue when testing. I don't see the need to keep this item open now.

**Comment by EmilieVrot** [comment]
I can see that you have implemented the See more button.
Thanks
