### ISSUE TITLE
[To discuss] Harmonize the dates with the European standards

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#22]

**Comment by carlabiscotti** [comment]
Hi Emilie, I've removed the "Network" reference since this will apply to all modules that display dates.
Do we have a final decision on the desired format? If yes, could you please add that to the ticket description? Thanks.

**Comment by EmilieVrot** [comment]
We agree on this format with Mathieu:
12 Jan 2012 - 30 Nov 2017 instead of 12/Jan/2012 - 30/Nov/2017

**Comment by carlabiscotti** [comment]
Hi Emilie, I will add this to the list of pending adjustments on the Network module. We will implement them all together as soon as possible.

**Comment by carlabiscotti** [comment]
Done!
