### ISSUE TITLE
[QA] Network - Question about the import of projects and organisations

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#23]
Some organizations are missing for the import (97 in the Excel file and 78 in the module).
I don't have access to the BO so I cannot change them but I have updated the Excel file on the short description.

Thanks

**Comment by clementprdhomme** [comment]
Bonjour @EmilieVrot,

Quel fichier contient la dernière version des organisations et projets ? `Organisations and projects - Version 2 (5OCT2023).xlsx` ?

**Comment by EmilieVrot** [comment]
Bonjour @clementprdhomme 
oui c'est bien celui-là (https://sites.inrae.fr/site/projet-orcasa/_layouts/15/WopiFrame.aspx?sourcedoc=%7B20BD8F22-F74E-4045-BA45-B9608A7DFDB0%7D&file=Organisations%20and%20projects%20-%20Version%202%20(5OCT2023).xlsx&action=default&IsList=1&ListId=%7B239D40F9-44DF-4443-82DC-6A0458D51053%7D&ListItemId=103 )

**Comment by carlabiscotti** [comment]
Hi Emilie, 

All projects and organizations are published now on the demo environment. Now that you and the rest of the group have access to the back office, can we agree that further adjustments and additional projects and organizations will be added directly to the back office? This way you can see the changes/new additions automatically and we reduce the workload related to managing this data.

**Comment by EmilieVrot** [comment]
Hello Carla,

I think the import hasn't worked completely.
We are good on the number of projects and organisations.
Yet in the Excel file, INRAE is linked to these projects: ORCaSa, MIXROOT-C, MaxRoot C, CarboSeq, Road4Schemes, SOMMIT, EnergyLink, ProbeField, AGROECOseqC, STEROPES
I can see in the Excel file that Yasmine didn't use the correct list of values to select the organisations. Anyways, it will be quite long for us to correct it manually.

Do you have a journal log when doing the import that reflects all the errors? It will be easier for me to correct it.

Thanks

**Comment by carlabiscotti** [comment]
Hi Emilie, Tiago who is in charge of managing the back office and the importing is on holiday until November 24th. Is it okay for you to have a response after that date?

**Comment by EmilieVrot** [comment]
Yes that's fine, I have strated to correct some of them directly in the BO but I just want to make with the journal of errors that I don't forget anything.
Thanks

**Comment by carlabiscotti** [comment]
Update from meeting with Emilie: she would like to know how the import managed projects and organizations that didn't have all the mandatory fields. Were they created anyway? 
In case they were not added, do we have the list of those that were not created?

**Comment by carlabiscotti** [comment]
Hi Emilie, 

Sorry for the delay on this. November was very busy with the events and now Tiago is on holiday again. I already asked him these questions. We'll come back to you in January.

**Comment by carlabiscotti** [comment]
Emilie, 

I got Tiago's response the entries missing required fields are not imported. There is a log that was generated when these were imported but is no longer available. 

Let me know if I can help you somehow.

**Comment by EmilieVrot** [comment]
Hello Carla, 

Thanks for your answer. It's unfortunate that I wasn't informed about the errors during the import. It's crucial moving forward that I'm notified about these kinds of issues so I can rectify errors as they occur. I will manually compare the list of projects and organizations (with the export functions in Strapi) to identify any discrepancies.

Best,
Emilie

**Comment by carlabiscotti** [comment]
Hi Emilie, 

You are right. I apologize for this mistake and will ensure we inform you earlier.

Best, 
Carla

**Comment by EmilieVrot** [comment]
Thanks Carla

**Comment by EmilieVrot** [comment]
Note: I have corrected the missing entries (or organisations not linked to projects). Attached the document I worked on (corrections are in green).
[Organisations and projects - Version 2 (5OCT2023).xlsx](https://github.com/Orcasa-Platform/orcasa/files/13811125/Organisations.and.projects.-.Version.2.5OCT2023.xlsx)
