### ISSUE TITLE
[QA] Geographical representation - Superposition of layers

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#32]
Layers are displayed via different colors on the map.
Yet, when we select different layers on the map, it is difficult to visualize all the layers based on the color.

Wouldn't it be preferable to use of ther visual effects (like different patterns) to distinguish them?

**Comment by EmilieVrot** [comment]
A comment on this:
If pattern is not really appropriate, it would be great to add a pop up window when we select 3 layers or more to indicate to the users that Selecting more than two layers will degrade loading time."
Thanks

**Comment by EmilieVrot** [comment]
As discussed in our meeting, you have planned to improve it by working on the colors

**Comment by carlabiscotti** [comment]
Hi Emilie, the final colors will be ready by the end of this sprint for you to check.

**Comment by EmilieVrot** [comment]
They seems fine to me. I suggest to close this item now. Let's see if we get further feedback from users cwhen all the layers will be implemented.
