### ISSUE TITLE
[To do] Geospatial data - Allow user to get pixel information on the map

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#34]
To apply for all the layers:
When I click on a specific location on the map, displaying the exact value (such as it is done on soilgrids)

**Comment by EmilieVrot** [comment]
Hi Carla, What do you want to discuss on that one?

**Comment by carlabiscotti** [comment]
This is for Vizzuality to discuss internally.

**Comment by EmilieVrot** [comment]
Hello Carla, we have to discuss how we will organize the period after v1.

**Comment by EmilieVrot** [comment]
JIRA #ORC-496
