### ISSUE TITLE
[QA] Menu on the left

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#36]
The menu is quite small of the left.
I think the color is not good for practices compared to the one in the homepage.

![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/66965ae4-ee1f-482f-8fa2-18783d629ded)

**Comment by carlabiscotti** [comment]
Hi Emilie, design adjustments have been applied during the current sprint. The changes will be available at the end of sprint 5 for you to review.

**Comment by EmilieVrot** [comment]
On the counter of the homepage in Figma, the colors are not good (at least for Practices).

**Comment by EmilieVrot** [comment]
Hello Carla,

There is still a problem on the homepage. The color of Projects is not good.
