### ISSUE TITLE
Network - Detailed view - Organisation

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#39]
1. The short description is missing in the detailed view (ex: Warsaw University of Life Science - SGGW)
2. When the type of organization if “Other”, the value entered manually should be displayed (ex: Promotional Centre for Family Farming – CPP)
3. When there is no website, do not display the button (ex: Promotional Centre for Family Farming – CPP)
4. Add the icons from the list of results (thematics and type of projects)

**Comment by carlabiscotti** [comment]
@EmilieVrot I have integrated this item to https://github.com/Orcasa-Platform/orcasa/issues/54
