### ISSUE TITLE
[To do] Network - Detailed view - Allow bullet points and line break in projects/organizations descriptions

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#40]
**User story**
As an admin drafting the description of projects and organizations from the back office, I want to format the text I enter so that it is better organized and easier for users to digest.

**Acceptance criteria**
- Admin users can add content in bullet points
- Admin users can start writing in a new line

**For reference**
Check the example of [Agricultural Producers Group TERRA]( https://demo.orcasa.dev-vizzuality.com/network/organization/61?map-settings=%7B%22basemap%22%3A%22basemap-light%22%2C%22labels%22%3A%22labels-dark%22%7D&bbox=%5B-111.5%2C-65.37%2C111.5%2C77.69%5D&layers=%5B%5D&layers-settings=%7B%7D) where Emilie has entered bullet points that are not displayed as such on the front end.

**Comment by EmilieVrot** [comment]
or do we have wiziwig options in Back Office?

**Comment by carlabiscotti** [comment]
Hi @EmilieVrot , I've re-phrased this item's title and description before discussing it with the team. Could you please take a look and confirm it makes sense to you?

**Comment by EmilieVrot** [comment]
Hi Carla, it is fine for me. If other formatting options are available, it could be useful (I am thinking of adding a picture/logo).
Thanks

**Comment by EmilieVrot** [comment]
JIRA #ORC-422
