### ISSUE TITLE
[QA] Network - General design

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#41]
Overall, I think the texts are very small in this module.

In the list of results:
![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/3d5e12a3-06d8-4242-a9db-35238198d132)

In the detailed view:
![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/b66ecbda-0553-4f71-b4ba-5772f0e2d8ac)

In the menu on the left:
![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/57d110fb-ee27-430b-8d36-6ebcd5b12638)

**Comment by EmilieVrot** [comment]
![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/bc1cd460-f9ed-437b-ae7d-2970c21619df)

**Comment by carlabiscotti** [comment]
Hi Emilie, design adjustments have been applied during the current sprint. The changes will be available at the end of sprint 5 for you to review.

**Comment by EmilieVrot** [comment]
Thanks Carla, the size of the texts is fine.
