### ISSUE TITLE
[To do] Integrate the final logo on the left bar of the modules

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#49]
As a user navigating the different tools within the platform, I want to easily see the name of the platform.

**Comment by carlabiscotti** [comment]
Emilie, this is done already. It will be available at the end of sprint 5 for you to check.

**Comment by EmilieVrot** [comment]
Thanks Carla. Please integrate the name of the platform with the logo on the left bar.
Best

**Comment by carlabiscotti** [comment]
Hi Emilie, the scope of this request is addressed. The final logo, as defined by the designers, is implemented. As I mentioned in another item, I want to reduce the back and forth on decisions made to safeguard the budget. For this new request for changing the way the logo was implemented on the design, would you mind adding a separate item to be prioritized later on? Thank you.

**Comment by EmilieVrot** [comment]
Hi Carla, when we presented the homepage, we said that we keep the logo of ORCaSa and include the name of the platform. For me this is not adressed as the logo should include the name.

Thanks

**Comment by EmilieVrot** [comment]
JIRA #ORC-423

**Comment by EmilieVrot** [comment]
JIRA #ORC-495
