### ISSUE TITLE
[Done] Network - Detailed view - Text changes and missing fields

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#54]
1. Add the short description and regions of intervention to the detailed view
2. For the fields with an icon on the preview (thematic and type of organizations), show these icons on the detailed view.
3. Change « Description » to « Description and outcomes”
4. Change « Countries of interventions » to “Countries of intervention”
5. For ORCasA, the country “Viêt Nam” is missing. DONE
6. For Afodek, the main area of intervention is not good. DONE
7. For CarboSeq, the country “Lituania” is missing. DONE
8. When the type of organization is “Other”, the value entered manually should be displayed (ex: Promotional Centre for Family Farming – CPP)

**Comment by carlabiscotti** [comment]
1. Several information is missing: short description, regions of intervention --> CB: The short description is meant to be shown only in the list preview. Regions of intervention we can add it in sprint 6. 
2. Adding the same icons as in the result list --> CB: Not sure what you mean with this. Could you please clarify?
3. Change « Description » by « Description and outcomes” --> CB: we'll do this change in sprint 6.
4. Change « Countries of interventions » by “Country of interventions of intervention” --> CB: Could you please double-check the wording suggested? It sounds incorrect to me. 
5. For ORCasA, the country “Viêt Nam” is missing --> CB: I've added it. The right spelling, according to the list, is Vietnam. That is why it wasn't showing.
6. For Afodek, the main area of intervention is not good --> CB: I've updated it to "Networking/structuring partnerships". Not sure why it was incorrect.
7. For CarboSeq, the country “Lituania” is missing --> CB: I've added it. The right spelling, according to the list, is Lithuania. That is why it wasn't showing.

**Comment by EmilieVrot** [comment]
1. short description is nice to keep in the detailed view because we tried not to repeat text from the short description to the "complete "description and, as the complete description is not compulsory, it will sometimes be empty.
2. it can be good for thematic and type of organization
3. ok
4. ok
5. ok
6. ok
7. ok

**Comment by EmilieVrot** [comment]
Other bugs (in issue 39 that has been closed):

8. When the type of organization is “Other”, the value entered manually should be displayed (ex: Promotional Centre for Family Farming – CPP)
9. When there is no website, do not display the button (ex: Promotional Centre for Family Farming – CPP)
10. Add the icons from the list of results (thematics and type of projects)

**Comment by carlabiscotti** [comment]
Hi Emilie, 8 and 10 are already listed in this item description. For 9 I've created a separate item for our convenience. https://github.com/Orcasa-Platform/orcasa/issues/65

**Comment by carlabiscotti** [comment]
Hi Emilie, 

2 This suggestion won't be implemented because it is not aligned with the design guidelines.
5 and 7. I see both countries available in the BO. What is the issue you are experiencing? 
8 I will ask the team to implement this.

**Comment by EmilieVrot** [comment]
Hello Carla,

2. OK
5 and 7. It should be my mistake I see them now
8. ok for doing it for V2

**Comment by EmilieVrot** [comment]
Hello Carla,

I prefer to leave this one open for V2, only for this task:

When the type of organization is “Other”, the value entered manually should be displayed (ex: Promotional Centre for Family Farming – CPP)

Thanks

**Comment by carlabiscotti** [comment]
Hi Emilie, aiming to have a clean list for the backlog prioritization. I created a separate item for what you mentioned above (https://github.com/Orcasa-Platform/orcasa/issues/163). 

I'm believe it is safe to close this item now, but let me know any comments.

**Comment by EmilieVrot** [comment]
ok for me
