### ISSUE TITLE
[QA] Geographical representation - Feedback from Eric

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#68]
Hello Carla,

We got some feedbacks from Eric to rename and rorder the layers.
I have seen in the BO that I can rename them (I have done it and reorder them) but I would like to know how to change the reference names and reorder the new groupe I have created.

All changes to applied are in the docuement: https://sites.inrae.fr/site/projet-orcasa/_layouts/15/WopiFrame.aspx?sourcedoc=%7B39F52AAD-21A4-471D-B976-A9EC7B173386%7D&file=ORCaSa%20-%20KP4SoilCarbon%20map%20layers%20and%20sources.xlsx&action=default&IsList=1&ListId=%7B239D40F9-44DF-4443-82DC-6A0458D51053%7D&ListItemId=undefined 

Thanks,
Emilie

**Comment by carlabiscotti** [comment]
Hi Emilie, can you please clarify what you mean by "reference name"?

**Comment by EmilieVrot** [comment]
Hi Carla,

I meant the text in yellow:
![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/0a984989-0002-4109-b2d1-df2173073080)

Thanks

**Comment by EmilieVrot** [comment]
Thanks Carla I have the access to that elements
