### ISSUE TITLE
[DONE] Strapi back office maintenance needs

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#74]
Hello Carla,

Can you share the info regarding the maintenance of this Back Office:

- Number of major/minor upgrades per year?
- Documentation for the upgrade?

Thanks

**Comment by carlabiscotti** [comment]
Hi Emilie, Sorry for the delay in coming back with this. Please find below the information provided by Tiago. 

Strapi seems to offer a roadmap of upcoming releases (either minor or major) nor does it seem to have a predictable pattern based on recent releases (https://github.com/strapi/strapi/releases). Update docs for strapi itself can be found in the official strapi docs (https://docs.strapi.io/dev-docs/update-version) and we expect those instructions to change and evolve with strapi itself, as it grows. Experience so far shows that updating strapi has been a quick, easy process for any developer familiar with nodejs.

**Comment by EmilieVrot** [comment]
Hello Carla,

Can we please let me know on which Strapi version we are?

During the time of the project, I would like to conduct with you at least one minor and one major release. The idea will be to document the process to put in place for this (actions to make, test to plan, etc.).
Can we plan this after the launch of the platform?

Thanks,
Emilie

**Comment by EmilieVrot** [comment]
JIRA # ORC-434
