### ISSUE TITLE
[To do] Back Office - Homepage and texts at the top of the modules

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#75]
Hello Carla,

Will we be able to edit the text of the homepage and the texts at the top of the modules?

Thanks,
Emilie

**Comment by carlabiscotti** [comment]
Hi Emilie, just to confirm that I received this request and will respond as soon as possible.

**Comment by carlabiscotti** [comment]
Hi Emilie, those texts can't be edited from the back office.

**Comment by EmilieVrot** [comment]
Hi Carla, Can you just explain how we will be able to edit the texts (where in the code)? Thanks

**Comment by carlabiscotti** [comment]
Hi Emilie, yes. We'll ensure this knowledge is transferred. I've added a separate issue for this https://github.com/Orcasa-Platform/orcasa/issues/117
