### ISSUE TITLE
[To do] Geospatial data - Stand out where high-resolution layers are located

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#76]
When we select the MRV layers, it is difficult to see on the global map where they are located.
We have to find a way to improve it.

**Comment by carlabiscotti** [comment]
Hi Emilie, thank you for reporting this. We plan to work on this after V1 is finished.

**Comment by EmilieVrot** [comment]
It is link to this request: https://basecamp.com/1756858/projects/19116498/todos/487400252
