### ISSUE TITLE
[To do] Network - Relational mapping

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#78]
Hi Carla,
We have a look to the relational mapping in the detailed view with Mathieu.
Is it possible to find a way to make this functionnality stands out? 
For instance adding colors on the different role of a partner on a project (the bold line is not enough), enlarge the text of the main organisation or project, we need to click on "Learn more" to access the linked project/organisation (can the link been made on the block containing its name?), etc.

**Comment by carlabiscotti** [comment]
Hi Emilie, thank you for your feedback.- These are all good ideas we will keep in mind to implement V1 is ready.- I'd like to create a new Milestone called V2 to group this and other items. Does it sound good to you?

**Comment by EmilieVrot** [comment]
Hello Carla, ok to implement this after V1 is finished. We just have to set up a date for v2 a few weeks before May 20th.
This one is a high priority for v2. Thanks

**Comment by EmilieVrot** [comment]
JIRA #ORC-419
