### ISSUE TITLE
[To discuss] Network - I cannot easily distinguish the project and organizations listed in the pop up window on the map

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#79]
It would be nice to add bullet points to the list of organisations and projects in the pop up windows on the map because it is difficult to distinguish them. And maybe also to enlarge the pop up itself when open (sometimes the list is long and users have to scroll down a lot).

**Comment by carlabiscotti** [comment]
Hi Emilie, thanks for your feedback. I will discuss this with Lidia.

**Comment by carlabiscotti** [comment]
Hi Emilie, this is something that can be improved. As with GitHub #78, we can implement this after V1 is finished.

**Comment by EmilieVrot** [comment]
Hello Carla, ok to implement this after V1 is finished. We just have to set up a date for v2 a few weeks before May 20th.

**Comment by EmilieVrot** [comment]
JIRA #ORC-418
