### ISSUE TITLE
[To discuss] Network - Faster access to the Project/Organizations filter

### ISSUE THREAD

**Issue by carlabiscotti** [Orcasa-Platform/orcasa#92]
Feedback from Emilie about the change implemented to the filters "project/organization" filters:

"It was nice to have it on top of the list of results. Plus, it would have helped to display only the relevant filters available (if we select "projects" for instance). Is it possible to keep them the way they were and just had their relevant colors?"

The filters "Projects" should be in orange like in the results and the filter "organizations" in blue.

**Comment by EmilieVrot** [comment]
Thanks Carla, this is a feedback shared with Mathieu. Best
