### ISSUE TITLE
[QA] Homepage - Enhancements

### ISSUE THREAD

**Issue by EmilieVrot** [Orcasa-Platform/orcasa#94]
1. Menu on top :  the colors are missing
2. Menu on top :  the link on “About the project” doesn’t work. It should go the ORCaSa website
3. Counters: I thought it would be animated
4. How can we go back to the homepage from the other pages ?

**Comment by carlabiscotti** [comment]
Hi Emilie, 

1. The implementation is according to the [design on Figma](https://www.figma.com/proto/DBXFTLd6nFBmg6fFE6P2cX/ORCaSa-Design-%5BInternal%5D?type=design&node-id=3066-18940&t=DaEFJT69sJGPw44O-0&scaling=min-zoom&page-id=165%3A38016&starting-point-node-id=3066%3A18940&show-proto-sidebar=1).
2. The link "About the project is working for me; it takes the user to the bottom of the page where the user can find information about ORCaSa.
3. There wasn't any animation planned on the design.
4. From the logo on the top-left corner.

**Comment by EmilieVrot** [comment]
Hello Carla,

1. Yet it is on the [Figma](https://www.figma.com/proto/fkoh3quv0lRInNgQxzW5AT/Design-%5BShared%5D?page-id=165%3A38016&type=design&node-id=1230-39145&viewport=367%2C1831%2C0.5&t=CCqumUO6kSB1URH9-1&scaling=min-zoom&starting-point-node-id=1230%3A39145&show-proto-sidebar=1) version. I don't know why it has been deleted at a moment:
![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/4daeeedf-fab9-4541-b886-c00765263535)

2. Ok for leaving it this way. But I remembered it was a chat we had with Lidia and Mathilde to put a link here to ORCaSa and maybe later on to change it for the IRC.
3. Yes it was planned to be added in the developed homepage:

![image](https://github.com/Orcasa-Platform/orcasa/assets/139888940/734ac1ba-700e-4c01-b0b0-cd62ec41dd49)
4. ok thanks!

**Comment by carlabiscotti** [comment]
Hi Emilie, 

Ok about 1 and 3, I will discuss with Lidia and Álvaro today. 

Best, 
Carla

**Comment by carlabiscotti** [comment]
Emilie, items 1 and 3 are ready in the demo environment.

**Comment by EmilieVrot** [comment]
Thanks it s ok for me
